"""empty message

Revision ID: 176fd3227500
Revises: e273e8c58fee
Create Date: 2020-06-28 16:18:30.521252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176fd3227500'
down_revision = 'e273e8c58fee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('listId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todolists', ['listId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'listId')
    op.drop_table('todolists')
    # ### end Alembic commands ###
