"""empty message

Revision ID: 55b9a0a44c85
Revises: 176fd3227500
Create Date: 2020-06-28 16:53:08.720882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55b9a0a44c85'
down_revision = '176fd3227500'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.drop_constraint('todos_listId_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    op.drop_column('todos', 'listId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('listId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_listId_fkey', 'todos', 'todolists', ['listId'], ['id'])
    op.drop_column('todos', 'list_id')
    # ### end Alembic commands ###
