"""empty message

Revision ID: ce6e6e9bcc27
Revises: 57b6b55bb24a
Create Date: 2020-06-28 19:54:52.833526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6e6e9bcc27'
down_revision = '57b6b55bb24a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todolists', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE todolists SET completed=False WHERE completed IS NULL')
    op.alter_column('todolists', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todolists', 'completed')
    # ### end Alembic commands ###
